export const initialCardData = [
    {
        id: 1,
        title: 'Test Account',
        unit: 't-sats',
        amount: '400,000',
        account: `Learn Bitcoin`,
        accountType: 'test',
        bitcoinicon: require('../assets/images/icons/icon_bitcoin_gray.png'),
    },
    {
        id: 2,
        title: 'Savings Account',
        unit: 'sats',
        amount: '60,000',
        account: 'Multi-factor security',
        accountType: 'secure',
        bitcoinicon: require('../assets/images/icons/icon_bitcoin_test.png'),
    },
    {
        id: 3,
        title: 'Checking Account',
        unit: 'sats',
        amount: '5,000',
        account: 'Fast and easy',
        accountType: 'regular',
        bitcoinicon: require('../assets/images/icons/icon_bitcoin_test.png'),
    },
    {
        id: 4,
        title: 'Add Account',
        unit: '',
        amount: '',
        account: '',
        accountType: 'add',
        bitcoinicon: require('../assets/images/icons/icon_add.png'),
    },
]