export const initialTransactionData = [
    {
        title: 'Spending accounts',
        date: '30 November 2019',
        time: '11:00 am',
        price: '0.025',
        transactionStatus: 'send',
    },
    {
        title: 'Spending accounts',
        date: '1 November 2019',
        time: '11:00 am',
        price: '0.015',
        transactionStatus: 'receive',
    },
    {
        title: 'Spending accounts',
        date: '30 Jully 2019',
        time: '10:00 am',
        price: '0.125',
        transactionStatus: 'receive',
    },
    {
        title: 'Saving accounts',
        date: '1 June 2019',
        time: '12:00 am',
        price: '0.5',
        transactionStatus: 'receive',
    },
    {
        title: 'Saving accounts',
        date: '11 May 2019',
        time: '1:00 pm',
        price: '0.1',
        transactionStatus: 'send',
    },
    {
        title: 'Spending accounts',
        date: '30 November 2019',
        time: '11:00 am',
        price: '0.025',
        transactionStatus: 'send',
    },
    {
        title: 'Spending accounts',
        date: '1 November 2019',
        time: '11:00 am',
        price: '0.015',
        transactionStatus: 'receive',
    },
    {
        title: 'Spending accounts',
        date: '30 Jully 2019',
        time: '10:00 am',
        price: '0.125',
        transactionStatus: 'receive',
    },
    {
        title: 'Saving accounts',
        date: '1 June 2019',
        time: '12:00 am',
        price: '0.5',
        transactionStatus: 'receive',
    },
    {
        title: 'Saving accounts',
        date: '12 May 2019',
        time: '1:00 pm',
        price: '0.1',
        transactionStatus: 'send',
    },
]