export const ACCOUNT_SYNC = "ACCOUNT_SYNC";
export const ACCOUNT_SYNC_FAIL = "ACCOUNT_SYNC_FAIL";
export const ACCOUNT_SYNC_SUCCESS = "ACCOUNT_SYNC_SUCCESS";

export const GET_QUOTE = "GET_QUOTE";
export const GET_QUOTE_FAIL = "GET_QUOTE_FAIL";
export const GET_QUOTE_SUCCESS = "GET_QUOTE_SUCCESS";

export const EXECUTE_ORDER = "EXECUTE_ORDER";
export const EXECUTE_ORDER_FAIL = "EXECUTE_ORDER_FAIL";
export const EXECUTE_ORDER_SUCCESS = "EXECUTE_ORDER_SUCCESS";

export const GET_BALANCES = "GET_BALANCES";
export const GET_BALANCES_FAIL = "GET_BALANCES_FAIL";
export const GET_BALANCES_SUCCESS = "GET_BALANCES_SUCCESS";

