export default [
  {
    language: 'English',
    displayTitle: 'English',
    iso: 'en',
    flag: '🇺🇸',
    country: 'United States',
    country_code: 'us',
  },
  {
    language: 'Spanish',
    displayTitle: 'Español',
    iso: 'es',
    flag: '🇪🇸',
    country: 'Spain',
    country_code: 'es',
  },
  {
    language: 'German',
    displayTitle: 'Deutsch',
    iso: 'de',
    flag: '🇩🇪',
    country: 'Gernamy',
    country_code: 'de',
  },
  {
    language: 'French',
    displayTitle: 'Français',
    iso: 'fr',
    flag: '🇫🇷',
    country: 'France',
    country_code: 'fr',
  },
  {
    language: 'Portuguese',
    displayTitle: 'Português',
    iso: 'pt',
    flag: '🇵🇹',
    country: 'Portugal',
    country_code: 'pt',
  },
  {
    language: 'Marathi',
    displayTitle: 'मराठी',
    iso: 'mr',
    flag: '🇮🇳',
    country: 'India',
    country_code: 'mr',
  },
  {
    language: 'Hindi',
    displayTitle: 'हिंदी',
    iso: 'hi',
    flag: '🇮🇳',
    country: 'India',
    country_code: 'hi',
  },
  {
    language: 'Gujarati',
    displayTitle: 'ગુજરાતી',
    iso: 'gu',
    flag: '🇮🇳',
    country: 'India',
    country_code: 'gu',
  },
  {
    language: 'Bengali',
    displayTitle: 'বাংলা',
    iso: 'bn',
    flag: '🇮🇳',
    country: 'India',
    country_code: 'bn',
  },
]

