require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '12.0'

def all_pods
    use_flipper!({'Flipper' => '0.140.0'})
    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])
    pod 'PDFGenerator'
    pod 'QRCoder'
    pod 'Firebase/Crashlytics'
    # Recommended: Add the Firebase pod for Google Analytics
    pod 'Firebase/Analytics'
end
target 'HEXA' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  all_pods
end
target 'HEXA Dev' do
  all_pods
end
target 'HEXA Stage' do
  all_pods
end
# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
      end
    end
    aggregate_target.user_project.save
  end
end
