
export enum NotificationType {
  FNF_REQUEST = 'FNF_REQUEST',
  FNF_TRANSACTION = 'FNF_TRANSACTION',
  RELEASE = 'RELEASE',
  FNF_REQUEST_ACCEPTED='FNF_REQUEST_ACCEPTED',
  FNF_REQUEST_REJECTED='FNF_REQUEST_REJECTED',
  FNF_KEEPER_REQUEST='FNF_KEEPER_REQUEST',
  FNF_KEEPER_REQUEST_ACCEPTED='FNF_KEEPER_REQUEST_ACCEPTED',
  FNF_KEEPER_REQUEST_REJECTED='FNF_KEEPER_REQUEST_REJECTED',
  GIFT_ACCEPTED = 'GIFT_ACCEPTED',
  GIFT_REJECTED = 'GIFT_REJECTED',
  CONTACT = 'contact',
  SECURE_XPUB = 'secureXpub',
  APPROVE_KEEPER = 'approveKeeper',
  UPLOAD_SEC_SHARE = 'uploadSecondaryShare',
  RESHARE= 'reShare',
  RESHARE_RESPONSE = 'reShareResponse',
  SM_UPLOADED_FOR_PK = 'smUploadedForPK',
  NEW_KEEPER_INFO = 'newKeeperInfo'
  }
