
export enum NotificationType {
  FNF_REQUEST = 'FNF_REQUEST',
  FNF_TRANSACTION = 'FNF_TRANSACTION',
  RELEASE = 'RELEASE',
  FNF_REQUEST_ACCEPTED='FNF_REQUEST_ACCEPTED',
  FNF_REQUEST_REJECTED='FNF_REQUEST_REJECTED',
  FNF_KEEPER_REQUEST='FNF_KEEPER_REQUEST',
  FNF_KEEPER_REQUEST_ACCEPTED='FNF_KEEPER_REQUEST_ACCEPTED',
  FNF_KEEPER_REQUEST_REJECTED='FNF_KEEPER_REQUEST_REJECTED',
  }
