export const REGULAR_ACCOUNT = 'REGULAR_ACCOUNT';
export const TEST_ACCOUNT = 'TEST_ACCOUNT';
export const SECURE_ACCOUNT = 'SECURE_ACCOUNT';
export const S3_SERVICE = 'S3_SERVICE';
export const TRUSTED_CONTACTS = 'TRUSTED_CONTACTS';
