-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3JCMkllkLayF7SLX
Wg3ax6RBmCw/5ONdlDOM+HnKsHmgCgYIKoZIzj0DAQehRANCAARpQ9V190jk8YHE
GmcPLLuUlxXaHwGpWbF46kyW8AeJEbFwySwZkizhdjDUGDUxLImYZKJ/0w9+oNYF
CGNNCLZ8
-----END PRIVATE KEY-----