# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :build do
    increment_version_code(gradle_file_path: "app/build.gradle")
    gradle(
      task: "clean assemble",
      build_type: "Release",
      # print_command: false,
      # flags: "--no-daemon --max-workers=8 --stacktrace --info",
    )
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to both Play Store and Huawei Store"
  lane :beta do
    build
    upload_to_play_store
  end

  desc "Deploy a new version to the Google Play"
  lane :play_store_deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
